name: Test
on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
        env:
          FORCE_COLOR: 0
      - run: yarn install --frozen-lockfile
      - name: Unit Tests
        run: yarn lerna run test
        env:
          TEST_NAME: unit
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
        env:
          FORCE_COLOR: 0
      - run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
        env:
          TEST_NAME: lint
